on: push

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: |
          echo "$GITHUB_WORKSPACE"
          df -h
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
          sudo rm -rf /usr/share/dotnet/shared/
          sudo rm -rf /usr/share/dotnet/host/
          sudo rm -rf /usr/share/dotnet/sdk/
          df -h
          sudo apt clean
          df -h
          docker rmi $(docker image ls -aq)
          df -h